# What is a jupyter notebook?

A jupyter notebook is like a lab notebook.
I can store text and code in the same place.

In [7]:
# this is a code cell

## subsection
I can write my text here

- list
- list
- list

# Python fundamentals

In [2]:
3 + 4 * 5

23

In [3]:
weight_kg = 60

In [11]:
weight_kg

60

In [5]:
60_weight

SyntaxError: invalid decimal literal (4080540362.py, line 1)

In [12]:
weight_60 = 60

In [8]:
weight = 60
Weight = 55

In [9]:
Weight

55

In [10]:
weight

60

In [13]:
print(weight_kg)

60


In [15]:
weight_kg

60

In [16]:
weight_lb = 2.2 * weight_kg

In [17]:
print(weight_lb)

132.0


In [18]:
patient_id = '001'

In [19]:
print(patient_id)

001


In [20]:
type(weight_kg)

int

In [21]:
weight_kg = 60.0

In [22]:
type(weight_kg)

float

In [24]:
type(patient_id)

str

In [25]:
weight_kg

60.0

In [26]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



# Lists

In [1]:
odds = [1, 3, 5, 7]

In [2]:
print('odds are: ', odds)

odds are:  [1, 3, 5, 7]


In [3]:
print('first element:', odds[0])

first element: 1


In [4]:
print('last element:', odds[3])

last element: 7


In [5]:
print('-1th element', odds[-1])

-1th element 7


In [6]:
print('-2th element', odds[-2])

-2th element 5


In [7]:
names = ['Curie', 'Darwing', 'Turing']

In [8]:
print('names is originally:', names)

names is originally: ['Curie', 'Darwing', 'Turing']


In [9]:
names[1] = 'Darwin'

In [10]:
print('final value of names:', names)

final value of names: ['Curie', 'Darwin', 'Turing']


In [11]:
name = 'Darwin'

In [13]:
name[-1]

'n'

In [14]:
name[0] = 'd'

TypeError: 'str' object does not support item assignment

In [15]:
sample_ages = [10, 12.5, 'Unknown']

In [16]:
odds

[1, 3, 5, 7]

In [18]:
odds.append(11)

In [19]:
odds

[1, 3, 5, 7, 11]

In [20]:
odds.pop(0)

1

In [21]:
odds

[3, 5, 7, 11]

In [22]:
odds.reverse()

In [23]:
odds

[11, 7, 5, 3]

In [24]:
odds.pop(2)

5

In [25]:
odds

[11, 7, 3]

In [26]:
odds = [3,5,7]

In [27]:
primes = odds

In [28]:
primes

[3, 5, 7]

In [29]:
odds

[3, 5, 7]

In [30]:
primes.append(2)

In [31]:
primes

[3, 5, 7, 2]

In [32]:
odds

[3, 5, 7, 2]

In [33]:
odds = [3,5,7]

In [34]:
primes = list(odds)

In [35]:
primes.append(2)

In [36]:
primes

[3, 5, 7, 2]

In [37]:
odds

[3, 5, 7]

In [38]:
name = 'dolores santos'

In [39]:
name

'dolores santos'

In [40]:
name[1]

'o'

In [41]:
name[0:7]

'dolores'

In [42]:
name[1:7]

'olores'

In [43]:
chromo = ['X', 'Y', '2', '3', '4']

In [44]:
chromo[2:5]

['2', '3', '4']

In [45]:
chromo[-1]

'4'

In [46]:
chromo[2:-1]

['2', '3']

In [49]:
veg = [['lettuce', 'lettuce', 'peppers', 'zucchini'],
       ['lettuce', 'lettuce', 'paprika', 'zucchini'],
       ['lettuce', 'cilantro', 'peppers', 'zucchini']]

In [50]:
print(veg[2])

['lettuce', 'cilantro', 'peppers', 'zucchini']


In [51]:
print(veg[0])

['lettuce', 'lettuce', 'peppers', 'zucchini']


In [ ]:
print(veg[0][0])

In [53]:
print(veg[1][2])

paprika


In [54]:
date = 'Monday 4 January 2016'

In [55]:
day = date[0:6]

In [59]:
day

''

In [58]:
day = ''

In [60]:
day = date[:6]

In [61]:
day

'Monday'

In [63]:
year = date[-4:]

In [64]:
year

'2016'

In [65]:
2 + 2

4

In [66]:
'2' + '2'

'22'

# Loops

In [1]:
odds = [ 1, 3, 5, 7]

In [2]:
print(odds[0])
print(odds[1])
print(odds[2])
print(odds[3])

1
3
5
7


In [5]:
for number in odds:
    print("value of number",number)
    print("multiplied", 2 * number)

value of number 1
multiplied 2
value of number 3
multiplied 6
value of number 5
multiplied 10
value of number 7
multiplied 14


In [6]:
for odd in odds:
    print(banana)

1
3
5
7


In [17]:
length = 100
names = ['Curie','Darwin','Turing']
for name in names:
    print("value of name",name)
    length = length + 1
    print("value of lenght", length)
print("lenght of list is:", length)

value of name Curie
value of lenght 101
value of name Darwin
value of lenght 102
value of name Turing
value of lenght 103
lenght of list is: 103


In [12]:
print(name)

Turing


In [20]:
name = 'Catalina'
names = ['Curie','Darwin','Turing']
print("Name before the loop",name)
length = 0
for name in names:
    print("value of name",name)
    length = length + 1

print("length after another loop", length)
print("what is the name after loop", name)

Name before the loop Catalina
value of name Curie
value of name Darwin
value of name Turing
length after another loop 3
what is the name after loop Turing


In [21]:
len(names)

3

# Loading Data

In [1]:
import numpy as np

In [3]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [4]:
type(data)

numpy.ndarray

In [5]:
data.shape

(60, 40)

In [7]:
data[0,0]

np.float64(0.0)

In [8]:
print('first value in data:', data[0,0])

first value in data: 0.0


In [9]:
print('middle value in data:', data[29, 19])

middle value in data: 16.0


In [10]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [11]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [12]:
print(data[:3, 36:])

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [13]:
print(np.mean(data))

6.14875


In [14]:
maxval = np.max(data)
minval = np.min(data)
stdval = np.std(data)

In [15]:
print('maximum value:', maxval)
print('minimum value:', minval)
print('standard deviation', stdval)

maximum value: 20.0
minimum value: 0.0
standard deviation 4.613833197118566


In [16]:
print('Minimum and maximum:', minval, ':', maxval)

Minimum and maximum: 0.0 : 20.0
